###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{ "username": "user25",
"email" : "una@here.ie",
"password" : "password10",
"roles": ["admin", "edit"]}

### login

POST http://localhost:3000/auth/local HTTP/1.1
content-type: application/json

{ "username": "user25",
"password" : "password1"}